version: '3.5'

services:
  nginx:
    container_name: ggiannit_nginx
    build: requirements/nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress
      - static
      - adminer

  mariadb:
    container_name: ggiannit_mariadb
    build: requirements/mariadb
    image: mariadb
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    container_name: ggiannit_wordpress
    build: requirements/wordpress
    image: wordpress
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env

  # bonus
  redis:
    container_name: ggiannit_redis
    build: requirements/bonus/redis
    image: redis
  adminer:
    container_name: ggiannit_adminer
    build: requirements/bonus/adminer
    image: adminer
  static:
    container_name: ggiannit_static
    build: requirements/bonus/static
    image: static
  ftp:
    container_name: ggiannit_ftp
    build: requirements/bonus/ftp
    image: ftp
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    restart: always
  browsh:
    container_name: ggiannit_browsh
    build: requirements/bonus/browsh
    image: browsh


networks:
  default:
    name: ggiannit_inception


volumes:
  wp:
    driver: local
    driver_opts:
      device: /root/wordpress
      o: bind
      type: none
  db:
    driver: local
    driver_opts:
      device: /root/database
      o: bind
      type: none
