version: '3.5'

services:
  nginx:
    container_name: ggiannit_nginx
    build: requirements/nginx
    ports:
      - 443:443
    # volumes:
    #   - wp:/var/www/html
    depends_on:
      - wordpress
  mariadb:
    container_name: ggiannit_mariadb
    build: requirements/mariadb
  #   volumes:
  #     - db:/var/lib/mysql
  wordpress:
    container_name: ggiannit_wordpress
    build: requirements/wordpress
    volumes:
      - wp:/var/www/html

networks:
  default:
    name: ggiannit_inception

volumes:
  wp:
    driver: local
    driver_opts:
      device: /root/wordpress
      o: bind
      type: none

#   db:
#     name: mariadb
#     driver: local
#     driver_opts:
#       device: -----
#       o: bind
#       type: none
