version: '3.5'

services:
  nginx:
    container_name: ggiannit_nginx
    build: requirements/nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
  mariadb:
    container_name: ggiannit_mariadb
    build: requirements/mariadb
  #   volumes:
  #     - db:/var/lib/mysql
  wordpress:
    container_name: ggiannit_wordpress
    build: requirements/wordpress
  #   # volumes:
  #   #   - ./wp-content:/var/www/html/wp-content

networks:
  default:
    name: ggiannit_inception

# volumes:
#   db:
#     name: mariadb
#     driver: local
#     driver_opts:
#       device: -----
#       o: bind
#       type: none
#   wp:
#     name: wordpress-content
#     driver: local
#     driver_opts:
#       device: -----
#       o: bind
#       type: none
